"""Fake but realistic data, generated by actually simulating table tennis.

Each player has a hidden skill number. Every point is a weighted coin flip based on
the skill gap; sets go to 11 (win by 2); matches are best of 5. So totals, sweeps,
deuces and upsets all come out with realistic frequencies.

Bonus: because you know the true skills, you can later check whether your Elo
actually recovers them. That's your first model test, for free.

Everything is deterministic: the same match id always produces the same result,
so an "upcoming" match becomes the same "finished" match on a later run.
"""
import math
import random
from datetime import date, datetime, time, timedelta, timezone

from app.providers.base import ProviderEvent, ProviderLeague, ProviderPlayer, ProviderSet

LEAGUES = [
    ProviderLeague(api_id="mock-czech", name="Czech Liga Pro"),
    ProviderLeague(api_id="mock-setka", name="Setka Cup"),
    ProviderLeague(api_id="mock-ttcup", name="TT Cup"),
    ProviderLeague(api_id="mock-elite", name="TT Elite Series"),
]

FIRST = ["Jan", "Petr", "Tomas", "Ondrej", "Martin", "Pavel", "Oleksandr", "Dmytro",
         "Andrii", "Yurii", "Mykola", "Serhii", "Lukas", "Filip", "Adam", "Vitalii"]
LAST = ["Novak", "Svoboda", "Dvorak", "Cerny", "Prochazka", "Kucera", "Shevchenko",
        "Kovalenko", "Bondarenko", "Tkachenko", "Kravets", "Melnyk", "Horak", "Marek",
        "Pospisil", "Hrytsenko"]

PLAYERS_PER_LEAGUE = 24
MATCHES_PER_DAY = 40      # per league, every 25 min from 06:00 UTC
POINT_SCALE = 0.12        # how much a skill gap shifts the per-point win chance
WALKOVER_RATE = 0.01
RETIRE_RATE = 0.01


class MockProvider:
    name = "mock"

    def __init__(self, seed: int = 42):
        self.seed = seed
        self._rosters = {lg.api_id: self._make_roster(lg.api_id) for lg in LEAGUES}

    # ---- public interface (matches DataProvider) ----

    def get_leagues(self) -> list[ProviderLeague]:
        return LEAGUES

    def get_upcoming(self, league_api_id: str) -> list[ProviderEvent]:
        today = datetime.now(timezone.utc).date()
        events = self._day_events(league_api_id, today) + self._day_events(
            league_api_id, today + timedelta(days=1)
        )
        return [e for e in events if e.status == "scheduled"]

    def get_ended(self, league_api_id: str, day: date) -> list[ProviderEvent]:
        return [e for e in self._day_events(league_api_id, day) if e.status != "scheduled"]

    def true_skill(self, player_api_id: str) -> float:
        """Hidden ground truth. Only for testing your models, never for predictions."""
        for roster in self._rosters.values():
            for player, skill in roster:
                if player.api_id == player_api_id:
                    return skill
        raise KeyError(player_api_id)

    # ---- internals ----

    def _make_roster(self, league_api_id: str):
        rng = random.Random(f"{self.seed}-{league_api_id}-roster")
        names = rng.sample([f"{f} {l}" for f in FIRST for l in LAST], PLAYERS_PER_LEAGUE)
        return [
            (ProviderPlayer(api_id=f"{league_api_id}-p{i:02d}", name=name), rng.gauss(0, 1))
            for i, name in enumerate(names)
        ]

    def _day_events(self, league_api_id: str, day: date) -> list[ProviderEvent]:
        league = next(lg for lg in LEAGUES if lg.api_id == league_api_id)
        roster = self._rosters[league_api_id]
        start = datetime.combine(day, time(6, 0), tzinfo=timezone.utc)
        now = datetime.now(timezone.utc)
        events = []

        for i in range(MATCHES_PER_DAY):
            api_id = f"{league_api_id}-{day:%Y%m%d}-{i:03d}"
            rng = random.Random(f"{self.seed}-{api_id}")  # per-match RNG = stable results
            (home, h_skill), (away, a_skill) = rng.sample(roster, 2)
            scheduled_at = start + timedelta(minutes=25 * i)

            ev = ProviderEvent(api_id=api_id, league=league, home=home, away=away,
                               scheduled_at=scheduled_at, status="scheduled")
            if scheduled_at + timedelta(minutes=20) <= now:  # assume it's over after 20 min
                ev.status, ev.sets = simulate_match(rng, h_skill, a_skill)
                if ev.status != "walkover":
                    ev.home_sets_won = sum(s.home_points > s.away_points for s in ev.sets)
                    ev.away_sets_won = len(ev.sets) - ev.home_sets_won
            # NOTE: this raw shape is made up. The real BetsAPI payload goes here later.
            ev.raw = ev.model_dump(mode="json", exclude={"raw"})
            events.append(ev)
        return events


def simulate_match(rng: random.Random, home_skill: float, away_skill: float):
    """Returns (status, sets)."""
    p_home_point = 1 / (1 + math.exp(-POINT_SCALE * (home_skill - away_skill)))

    roll = rng.random()
    if roll < WALKOVER_RATE:
        return "walkover", []
    retire_after_set = rng.randint(1, 4) if roll < WALKOVER_RATE + RETIRE_RATE else None

    sets: list[ProviderSet] = []
    home_won = away_won = 0
    while home_won < 3 and away_won < 3:
        h = a = 0
        while not (max(h, a) >= 11 and abs(h - a) >= 2):
            if rng.random() < p_home_point:
                h += 1
            else:
                a += 1
        sets.append(ProviderSet(set_number=len(sets) + 1, home_points=h, away_points=a))
        home_won += h > a
        away_won += a > h
        if retire_after_set == len(sets) and home_won < 3 and away_won < 3:
            return "retired", sets
    return "finished", sets
